version: '2'
services:
    jh4uaa-mysql:
        container_name: jh4uaa-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/JH4UAA/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jh4uaa
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
